version: '3.7'

services:
  nginx:
    image: nginx:1-alpine
    volumes: 
      - ./nginx-data/demo:/sites/demo
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - '80:80'
      - '443:443'